# Generated by Django 4.2.4 on 2023-09-04 15:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('seminar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField()),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamemodel',
            options={'ordering': ['-played']},
        ),
        migrations.AlterModelManagers(
            name='gamemodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
