# Generated by Django 4.2.4 on 2023-09-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hw2_app', '0002_alter_goods_date_item_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reg_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
