# Generated by Django 4.2.4 on 2023-09-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hw2_app', '0003_alter_client_reg_date_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='product_image',
            field=models.ImageField(default=0, upload_to='media/images/'),
            preserve_default=False,
        ),
    ]
