# Generated by Django 4.2.4 on 2023-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hw2_app', '0004_goods_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
